name: Python package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint
        run: |
          poetry run flake8 add.py test_add.py

      - name: Test with pytest
        run: |
          poetry run pytest
